version: "3.2"
services:
  pythonapp:
    restart: always
    container_name: python-app
    build:
      context: python
      dockerfile: deployments/app/Dockerfile
    ports:
      - 5000:5000

  mongodb:
    restart: always
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles

  springboot:
    restart: always
    build: .
    container_name: springboot
    working_dir: /opt/app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - mongodb